name: 自动同步订阅节点

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次
  workflow_dispatch: # 允许手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 抓取并转换节点
        run: |
          # 这里换成你刚才测试成功的那个 Worker 长链接
          # 注意：去掉了原本会报错的 &config=... 参数，让它使用默认兼容配置
          curl -L "https://sub-convert.taoisming.workers.dev/sub?target=singbox&url=https%3A%2F%2Fsep.bbdmfetch.com%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D64ba85477145c43f96c1ddffa339287f" -o nodes.json

      - name: 提交到仓库
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add nodes.json
          git commit -m "更新节点数据" || exit 0
          git push
